# -*- coding: utf-8 -*-
"""web scraping

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zy9I11tihHd6fDrJDLuRVXYRxQd6gLaE
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

# Step 1: Request the webpage
url = "http://books.toscrape.com/"
response = requests.get(url)

# Step 2: Parse HTML content
soup = BeautifulSoup(response.text, 'html.parser')

# Step 3: Find book listings
books = soup.find_all('article', class_='product_pod')

# Step 4: Extract title and price
data = []
for book in books:
    title = book.h3.a['title']
    price = book.find('p', class_='price_color').text
    data.append({'Title': title, 'Price': price})

# Step 5: Convert to DataFrame and save to CSV
df = pd.DataFrame(data)
df.to_csv('books.csv', index=False)

print("✅ books.csv created successfully.")
print(df.head())  # Preview first 5 rows

